version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node
    steps:
      - checkout
      - run: npm ci
      - run:
          background: true
          command: node server.js
      - run: sleep 20s && curl http://127.0.0.1:8000/

workflows:
  workflows:
    jobs:
      - build