version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node
    steps:
      - checkout
      - run: npm ci
      - run:
          background: true
          command: node server.js
      - run: |
          echo "some text"
          #$(npm bin)/wait-on http://127.0.0.1:8000/test
          #curl http://127.0.0.1:8000/test
          $(npm bin)/wait-on http://127.0.0.1:8000/health_check/

workflows:
  workflows:
    jobs:
      - build